galaxy/models/post.py
from galaxy import db
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length
from datetime import datetime


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return "Post('{}', '{}')".format(self.title, self.date_posted)


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=100)])
    content = TextAreaField('Content')
    submit = SubmitField('Post')

galaxy/routes/post.py
from flask_login import login_required, current_user
from flask import request, Blueprint, render_template, redirect, url_for, flash, abort, current_app
from ..models.post import PostForm, Post
from .. import db
post = Blueprint('post', __name__)


@post.route('/post', methods=['GET'])
def post_home():
    return 'post'


@post.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        p = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        db.session.add(p)
        db.session.commit()
        flash(message='Your post has been created!', category='success')
        return redirect(url_for('main.home'))
    return render_template('views/create_post.html', title='New Post', form=form)


@post.route('/post/<int:post_id>', methods=['GET'])
def single_post(post_id):
    p = Post.query.get_or_404(post_id)
    return render_template('views/post.html', title=p.title, post=p)


@post.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    form = PostForm()
    p = Post.query.get_or_404(post_id)
    if p.author != current_user:
        abort(403)
    if form.validate_on_submit():
        p.title = form.title.data
        p.content = form.content.data
        db.session.commit()
        flash(message='Your post has been updated!', category='success')
        return redirect(url_for('post.single_post', post_id=p.id))
    form.title.data = p.title
    form.content.data = p.content
    form.submit.label.text = 'Update'
    return render_template('views/create_post.html', title='Update Post', form=form, legend='Update Post')


@post.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    p = Post.query.get_or_404(post_id)
    if p.author != current_user:
        abort(403)
    db.session.delete(p)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

galaxy/routes/user.py
from flask import request, Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, logout_user, current_user, login_required
from galaxy.models.user import LoginForm, AccountForm, ResetPasswordRequestForm, ResetPasswordForm, User
from galaxy import db, bcrypt, mail
from flask_mail import Message
from PIL import Image
import secrets
import os

user = Blueprint('user', __name__)


@user.route('/register', methods=['GET', 'POST'])
def register():
    flash(message=f'暂不提供注册功能', category='warning')
    return redirect(url_for('main.home'))
    # if current_user.is_authenticated:
    #     return redirect(url_for('main.home'))
    # form = RegistrationForm()
    # if form.validate_on_submit():
    #     hashed_password = bcrypt.generate_password_hash(form.password.data)
    #     u = User(username=form.username.data, email=form.email.data, password=hashed_password)
    #     db.session.add(u)
    #     db.session.commit()
    #     flash(message=f'Your account has been created! You are now able to log in', category='success')
    #     return redirect(url_for('user.login'))
    # return render_template('views/register.html', title='注册', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u and bcrypt.check_password_hash(u.password, form.password.data):
            login_user(u, remember=form.remember.data)
            flash(message='登录成功', category='success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(message='Login Unsuccessful! Please check email and password.', category='danger')
    return render_template('views/login.html', title='注册', form=form)


@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@user.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = AccountForm()
    image_file = url_for('static', filename='profile_pics/{}'.format(current_user.image_file))
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('user.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('views/account.html', title='账户', form=form, image_file=image_file)


@user.route('/reset-password-request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        send_email(u)
        flash('重置密码的邮件发送成功', 'info')
        return redirect(url_for('user.login'))
    return render_template('views/reset-password-request.html', title='Reset password', form=form)


@user.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm()
    u = User.verify_reset_token(token)
    if u is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_password_request'))
    if form.validate_on_submit():
        u.password = bcrypt.generate_password_hash(form.password.data)
        db.session.commit()
        flash('Your password has been reset!', 'success')
        return redirect(url_for('user.login'))
    return render_template('views/reset-password.html', title='Reset password', form=form)


def send_email(u):
    token = u.get_reset_token()
    msg = Message('重置你的密码',
                  sender='no-replay@demo.com',
                  recipients=[u.email])
    msg.body = f'''
     点击连接以重置你的密码{url_for('user.reset_password', token=token, _external=True)}
    '''
    msg.html = f'''
         点击连接以重置你的密码 
         <a href="{url_for('user.reset_password', token=token, _external=True)}">
{url_for('user.reset_password', token=token, _external=True)}</a> 
        '''
    mail.send(msg)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_fn)

    size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(size)
    i.save(picture_path)

    return picture_fn

galaxy/templates/views/about.html
{% extends 'layout/base_layout.html' %}

{% block content %}
    <div class="media content-section">
        <div class="media-body">
            <p>网站开发用到的技术有 Flask、flask-sqlalchemy、flask-wtf 等</p>
            <p>网站采用 gunicorn 和 supervisor 部署在 CentOS7 服务器上</p>
            <hr>
        </div>
    </div>
{% endblock %}

galaxy/templates/views/account.html
{% extends 'layout/base_layout.html' %}

{% block content %}
    <div class="content-section">
         <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
         <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

{% endblock %}

galaxy/templates/views/create_post.html
{% extends 'layout/base_layout.html' %}
{% block content %}
    <div class="content-section">
        <form action="" method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend or 'New Post' }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

{% block script %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ url_for('static', filename='js/ckeditor/plugins/image-uploader/plugin.js') }}"></script>
    <script>
        function ImageUploaderPlugin(editor) {
            editor.plugins.get('FileRepository').createUploadAdapter = (loader) => {
                return new ImageUploader(loader)
            }
        }

        ClassicEditor
            .create(document.querySelector('#content'), {
                extraPlugins: [ImageUploaderPlugin]
            })
            .catch(error => {
                console.error(error)
            })
    </script>
{% endblock %}

galaxy/templates/views/index.html
{% extends 'layout/base_layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img alt="img" class="rounded-circle article-img--index" src={{ url_for('static', filename='profile_pics/{}'.format(post.author.image_file)) }}>
            <div class="media-body">
                <div class="article-metadata">
                <small class="text-muted">{{ post.author.username }} &nbsp; {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('post.single_post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ (post.content | html2text)[0:100] + "..." }}</p>
            </div>
        </article>
    {% endfor %}
    {% if posts.pages > 1 %}
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-end">
                <li class="page-item {% if 1 == posts.page %}disabled{% endif %}"><a class="page-link" href="{{ url_for('main.home', page=posts.page - 1) }}">Previous</a></li>
                {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                    {% if page_num %}
                        <li class="page-item {% if page_num == posts.page %}disabled{% endif %}"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
                    {% endif %}
                {% endfor %}
                <li class="page-item {% if posts.pages == posts.page %}disabled{% endif %}"><a class="page-link" href="{{ url_for('main.home', page=posts.page + 1) }}">Next</a></li>
            </ul>
        </nav>
    {% endif %}

{% endblock %}

galaxy/templates/views/login.html
{% extends "layout/base_layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('user.reset_password_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock %}

galaxy/templates/views/post.html
{% extends 'layout/base_layout.html' %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/ck-content-style.css') }}"></link>
{% endblock %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <img alt="img" class="rounded-circle article-img" src={{ url_for('static', filename='profile_pics/{}'.format(post.author.image_file)) }}>
                <small class="text-muted">{{ post.author.username }} &nbsp; {{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm m-1" href={{ url_for('post.update_post', post_id=post.id) }}>Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2>{{ post.title }}</h2>
            <div class="article-content ck-content">{{ post.content | safe }}</div>
        </div>
    </article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirm delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure to delete this post?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form method="POST" action={{ url_for('post.delete_post', post_id=post.id) }}>
                <input type="submit" class="btn btn-danger" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

galaxy/templates/views/register.html
{% extends "layout/base_layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="{{ url_for('user.register') }}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
        </small>
    </div>
{% endblock %}

galaxy/templates/views/reset-password-request.html
{% extends 'layout/base_layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span><br>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}

galaxy/templates/views/reset-password.html
{% extends 'layout/base_layout.html' %}

{% block content %}
     <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
               <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock %}