galaxy/routes/main.py
from flask import render_template, request, Blueprint
from ..models.post import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template('views/index.html', posts=posts)


@main.route('/about')
def about():
    return render_template('views/about.html')

galaxy/routes/post.py
from flask_login import login_required, current_user
from flask import request, Blueprint, render_template, redirect, url_for, flash, abort, current_app
from ..models.post import PostForm, Post
from .. import db
post = Blueprint('post', __name__)


@post.route('/post', methods=['GET'])
def post_home():
    return 'post'


@post.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        p = Post(title=form.title.data, content=form.content.data, user_id=current_user.id)
        db.session.add(p)
        db.session.commit()
        flash(message='Your post has been created!', category='success')
        return redirect(url_for('main.home'))
    return render_template('views/create_post.html', title='New Post', form=form)


@post.route('/post/<int:post_id>', methods=['GET'])
def single_post(post_id):
    p = Post.query.get_or_404(post_id)
    return render_template('views/post.html', title=p.title, post=p)


@post.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    form = PostForm()
    p = Post.query.get_or_404(post_id)
    if p.author != current_user:
        abort(403)
    if form.validate_on_submit():
        p.title = form.title.data
        p.content = form.content.data
        db.session.commit()
        flash(message='Your post has been updated!', category='success')
        return redirect(url_for('post.single_post', post_id=p.id))
    form.title.data = p.title
    form.content.data = p.content
    form.submit.label.text = 'Update'
    return render_template('views/create_post.html', title='Update Post', form=form, legend='Update Post')


@post.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    p = Post.query.get_or_404(post_id)
    if p.author != current_user:
        abort(403)
    db.session.delete(p)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

galaxy/routes/user.py
from flask import request, Blueprint, render_template, redirect, url_for, flash, current_app
from flask_login import login_user, logout_user, current_user, login_required
from galaxy.models.user import LoginForm, AccountForm, ResetPasswordRequestForm, ResetPasswordForm, User
from galaxy import db, bcrypt, mail
from flask_mail import Message
from PIL import Image
import secrets
import os

user = Blueprint('user', __name__)


@user.route('/register', methods=['GET', 'POST'])
def register():
    flash(message=f'暂不提供注册功能', category='warning')
    return redirect(url_for('main.home'))
    # if current_user.is_authenticated:
    #     return redirect(url_for('main.home'))
    # form = RegistrationForm()
    # if form.validate_on_submit():
    #     hashed_password = bcrypt.generate_password_hash(form.password.data)
    #     u = User(username=form.username.data, email=form.email.data, password=hashed_password)
    #     db.session.add(u)
    #     db.session.commit()
    #     flash(message=f'Your account has been created! You are now able to log in', category='success')
    #     return redirect(url_for('user.login'))
    # return render_template('views/register.html', title='注册', form=form)


@user.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        if u and bcrypt.check_password_hash(u.password, form.password.data):
            login_user(u, remember=form.remember.data)
            flash(message='登录成功', category='success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(message='Login Unsuccessful! Please check email and password.', category='danger')
    return render_template('views/login.html', title='注册', form=form)


@user.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@user.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = AccountForm()
    image_file = url_for('static', filename='profile_pics/{}'.format(current_user.image_file))
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('user.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('views/account.html', title='账户', form=form, image_file=image_file)


@user.route('/reset-password-request', methods=['GET', 'POST'])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        u = User.query.filter_by(email=form.email.data).first()
        send_email(u)
        flash('重置密码的邮件发送成功', 'info')
        return redirect(url_for('user.login'))
    return render_template('views/reset-password-request.html', title='Reset password', form=form)


@user.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm()
    u = User.verify_reset_token(token)
    if u is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_password_request'))
    if form.validate_on_submit():
        u.password = bcrypt.generate_password_hash(form.password.data)
        db.session.commit()
        flash('Your password has been reset!', 'success')
        return redirect(url_for('user.login'))
    return render_template('views/reset-password.html', title='Reset password', form=form)


def send_email(u):
    token = u.get_reset_token()
    msg = Message('重置你的密码',
                  sender='no-replay@demo.com',
                  recipients=[u.email])
    msg.body = f'''
     点击连接以重置你的密码{url_for('user.reset_password', token=token, _external=True)}
    '''
    msg.html = f'''
         点击连接以重置你的密码 
         <a href="{url_for('user.reset_password', token=token, _external=True)}">
{url_for('user.reset_password', token=token, _external=True)}</a> 
        '''
    mail.send(msg)


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/profile_pics', picture_fn)

    size = (125, 125)
    i = Image.open(form_picture)
    i.thumbnail(size)
    i.save(picture_path)

    return picture_fn

galaxy/templates/layout/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
        <link href="{{ url_for('static', filename='images/favicon.ico') }}" rel="shortcut icon" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
        {% if title %}
        <title>{{ title }} - Flask Blog</title>
        {% else %}
            <title>Flask Blog</title>
        {% endif %}
    {% endblock %}
</head>
<body>
     <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-kashmir fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('post.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('user.account') }}">
                    <img width="24" class="rounded-circle" src="{{ url_for('static', filename='profile_pics/{}'.format(current_user.image_file))}}" alt="">
                    {{ current_user.username }}
                </a>
                <a class="nav-item nav-link" href="{{ url_for('user.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('user.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-dismissible alert-{{ category }}" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    {% block footer %}
    {% endblock %}
    {% block script %}
        <script src="{{ url_for('static', filename='js/jquery/jquery-3.3.1.slim.min.js') }}" defer></script>
        <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.min.js') }}" defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                defer
                crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>